---

#- name: makemigrations
#  django_manage:
#    command: makemigrations
#    virtualenv: "{{ django_venv_path }}"
#    app_path: "/home/{{ chessfracture_user }}/chessfracture/django/mysite"

- name: migrate
  django_manage:
    command: migrate
    virtualenv: "{{ django_venv_path }}"
    app_path: "/home/{{ chessfracture_user }}/chessfracture/django/mysite"

- name: restart uwsgi
  service:
    name: uwsgi
    state: restarted
