---
# tasks file for chessfracture
- name: test connection
  ping:

- name: install requirements
  yum:
    name:
      - yum-utils
      - zip
      - xorg-x11-server-Xorg
      - xorg-x11-xauth
      - xorg-x11-server-utils
      - mesa-dri-drivers
      - git
      - python2-pip
      - gcc
      - openssl-devel
      - vim
      - bash-completion
      - tcpdump

- name: copy /etc/systemd/system.conf
  copy:
    src: etc/systemd/system.conf
    dest: /etc/systemd/system.conf
    owner: root
    group: root
    mode: 0644

- name: "create user {{ chessfracture_user }}"
  user:
    name: "{{ chessfracture_user }}"

- name: sync files
  synchronize:
    src: "{{ playbook_dir }}/.."
    dest: "/home/{{ chessfracture_user }}/chessfracture"
    rsync_path: "sudo -u {{ chessfracture_user }} rsync"
    delete: yes
  become_user: "{{ chessfracture_user }}"

- name: django
  include: django.yml

